version: '3'
services:
  webapp:
    image: aolifu/amazon-adv-boot:v1
    container_name: amazon-adv-boot
    network_mode: "host"
    ports:
      - "8085:8085"
    environment:
      - spring.cloud.nacos.username=oneanswer
      - spring.cloud.nacos.password=oneanswer
      - TZ=Asia/Shanghai
    volumes:
      - /root/log4wimoor/amazon-adv-boot/logs:/root/log4wimoor/amazon-adv-boot/logs
