version: '3'
services:
  webapp:
    image: aolifu/wimoor-auth:v1
    container_name: wimoor-auth
    network_mode: "host"
    ports:
      - "8085:8085"
    environment:
      - spring.cloud.nacos.username=oneanswer
      - spring.cloud.nacos.password=oneanswer
      - TZ=Asia/Shanghai
    volumes:
      - /root/log4wimoor/wimoor-auth/logs:/root/log4wimoor/wimoor-auth/logs
